default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: postgres
  user: postgres
 
 
development:
  <<: *default
  database: Exchange_development
 
 
test:
  <<: *default
  database: Exchange_test

  
production:
  <<: *default
  database: Exchange_production
  username: Exchange
  password: <%= ENV['EXCHANGE_DATABASE_PASSWORD'] %>